1 - function sum
js-tasks-ru/js-20221121_malakhov5041 pull request #1
Opened 2022-11-29 05:36 UTC by soniclord

2022-11-29 05:36 UTC, jsru commented
Спасибо за отправленный пулриквест, теперь @dosandk должен запустить тесты.

2022-12-01 14:51 UTC, dosandk commented on 01-intro/1-sum/index.js
> +  return m + n;
good 👍

2022-12-01 14:52 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  let arr2 = arr.slice();
`arr2` не самое удачное имя для переменной

2022-12-01 14:52 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  let arr2 = arr.slice();
здесь явно нужно использовать `const`

2022-12-01 14:53 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  let arr2 = arr.slice();
используйте `[...arr]` для копирования массива

2022-12-01 14:53 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    arr2.reverse();
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2022-12-01 14:54 UTC, dosandk requested changes
решение `sortStrings` следует поправить

2022-12-04 15:53 UTC, dosandk approved these changes
good 👍

2022-12-04 15:53 UTC, merged